version: "3.9"

networks:
  dev:
    driver: bridge

services:
  app:
    container_name: iiko
    image: iiko
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - app_database
    networks:
      - dev
    
  app_database:
    image: postgres:15.3
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Iiko
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - dev
