version: "3.9"

services:
  db:
    image: postgres:15.3
    container_name: db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Iiko
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  