using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Aiko.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class MakeSystemIdAutoGenerated_2 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<Guid>(
                name: "system_id",
                table: "Entities",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldDefaultValueSql: "uuid_generate_v4");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterColumn<Guid>(
                name: "system_id",
                table: "Entities",
                type: "uuid",
                nullable: false,
                defaultValueSql: "uuid_generate_v4",
                oldClrType: typeof(Guid),
                oldType: "uuid");
        }
    }
}
