// <auto-generated />
using System;
using Aiko.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aiko.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241126121419_MakeSystemIdAutoGenerated_2")]
    partial class MakeSystemIdAutoGenerated_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aiko.Domain.Entity", b =>
                {
                    b.Property<long>("ClientId")
                        .HasColumnType("bigint")
                        .HasColumnName("client_Id");

                    b.Property<Guid>("SystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("system_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("ClientId");

                    b.ToTable("Entities");
                });
#pragma warning restore 612, 618
        }
    }
}
